# -*- coding: utf-8 -*-
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

OUTPUT = r"C:\Users\gabriel.evangelista\Documents\ClaudeGL\Buscas_PF_PJ.xlsx"

TEAL      = "0E8FA3"
TEAL_DARK = "0A6A7A"
WHITE     = "FFFFFF"
GRAY_LIGHT = "F2F2F2"

# Apenas Pessoa Física
PF_EXCLUSIVO = [
    "Antecedentes Criminais / MG",
    "Antecedentes Criminais / Polícia Federal / Emitir",
    "Antecedentes Criminais / SP",
    "CNIS / Pré-inscrição",
    "Conselho Federal de Psicologia / Cadastro",
    "Conselho Nacional de Justiça / Mandados de Prisão",
    "Conselho Nacional de Justiça / SEEU / Processos",
    "CRCP / Central de Registros de Certificados Profissionais",
    "Portal da Transparência / Servidor Público",
    "Receita Federal / CPF",
    "Receita Federal / IRPF",
    "Registro Civil / Validar Certidão Eletrônica",
    "Tribunal / TJMT / Certidão do 1º Grau (Pessoa Física)",
    "Tribunal / TSE / Certidão de Quitação Eleitoral",
    "Tribunal / TSE / Doadores e Fornecedores",
    "Tribunal / TSE / Situação Eleitoral",
    "UNSCCL - United Nations Security Council Consolidated List (PF)",
    "INTERPOL (PF)",
    "OFAC - Sanções (PF)",
    "FBI - Most Wanted (PF)",
]

# Apenas Pessoa Jurídica
PJ_EXCLUSIVO = [
    "ANP / Base de Distribuição",
    "ANP / Certificados",
    "ANP / Instalações do SIMP",
    "ANP / Instalações do SIMP / Distribuidores Autorizados",
    "ANP / Postos",
    "ANP / Revendas GLP",
    "ANTT / SIFAMA / Consultar Multas",
    "ANTT / SIFAMA / Download de Auto de Infração",
    "ANTT / SIFAMA / Lista de Autos de Infração",
    "ANTT / SIFAMA / Segunda Via de Boletos",
    "ANVISA / Funcionamento de Empresa Nacional",
    "B3 / Participantes",
    "Caixa / Regularidade do Empregador (FGTS)",
    "CARF / Processo",
    "Comprot / Processo",
    "Controladoria-Geral da União / Certidão Negativa Correcional (CGU-PJ, CEIS, CNEP e CEPIM)",
    "CVM / Participante",
    "CVM / Processos Administrativos Sancionadores",
    "CVM / Processos Sancionadores Julgados",
    "DNIT / Infrações (CNPJ)",
    "FGTS / Emissão de Guia Rápida",
    "FGTS / Guia de Arrecadação",
    "Junta Comercial / SP / Certidão Simplificada",
    "Ministério da Fazenda / SPED",
    "MTE / Processos por Empregador",
    "Receita Federal / CNPJ",
    "Receita Federal / MEI",
    "Receita Federal / REDESIM / Acompanhamento de Protocolo",
    "Receita Federal / Radar (Habilitação Comércio Exterior)",
    "Receita Federal / SIMEI (Declaração Anual)",
    "Receita Federal / Simei / MEI / Emissão de Guia de Parcelamento",
    "Receita Federal / Simples (DASN SIMEI)",
    "Receita Federal / Simples (Emissão de DAS de MEI)",
    "Receita Federal / Simples (Listagem de Períodos para Emissão de DAS)",
    "Receita Federal / Simples / MEI / Emissão de Guia de Parcelamento",
    "Receita Federal / Simples Nacional",
    "Secretaria de Inspeção do Trabalho / CAEPI",
    "TCU / Consulta Consolidada de Pessoa Jurídica (APF)",
    "FINCEN - Financial Crimes Enforcement Network (PJ)",
]

# Aplicável a ambos
AMBOS = [
    "ANTT / Transportador",
    "ANTT / Transporte Rodoviário Internacional de Cargas (TRIC)",
    "ANTT / Veículo",
    "ANVISA / Processo",
    "Banco Central do Brasil (BCB) / Relatório de Cheques sem Fundos",
    "Banco Central do Brasil (BCB) / Valores a Receber",
    "Buscador / Google",
    "Cadastro Ambiental Rural / Demonstrativo",
    "Cadastro Ambiental Rural / Demonstrativo (PDF)",
    "Cadastro Ambiental Rural / Download de Shapefile",
    "Cadastro Ambiental Rural / Imóvel",
    "Cadastur / Prestadores",
    "CADE / Processos",
    "CENPROT SP / Protestos",
    "Conselho Nacional de Justiça / Improbidade Administrativa e Inelegibilidade",
    "Conselho Nacional de Justiça / Serventias Extrajudiciais (Lista)",
    "Controladoria-Geral da União / Certidão Negativa Correcional (ePAD e CGU-PAD)",
    "GIT Cidadão (PR) / Multas",
    "GIT Cidadão (PR) / Notificações",
    "IBAMA / Autuações Ambientais",
    "IBAMA / Certidão de Débitos",
    "IBAMA / Certidão de Embargos (Nada Consta)",
    "IBAMA / Certificado de Regularidade",
    "IBGE / Área territorial brasileira",
    "IBGE / Código de Município",
    "IEPTB (CENPROT) / Protestos",
    "INPI / Marcas por CPF/CNPJ",
    "MPF / Amazônia Protege",
    "MPF / Lava-Jato",
    "MPF / Processos",
    "MPT / AC e RO / Certidão Negativa de Feitos",
    "MPT / AL / Certidão Negativa de Feitos",
    "MPT / AM e RR / Certidão Negativa de Feitos",
    "MPT / AP e PA / Certidão Negativa de Feitos",
    "MPT / BA / Certidão Negativa de Feitos",
    "MPT / CE / Certidão Negativa de Feitos",
    "MPT / DF e TO / Certidão Negativa de Feitos",
    "MPT / ES / Certidão Negativa de Feitos",
    "MPT / GO / Certidão Negativa de Feitos",
    "MPT / MA / Certidão Negativa de Feitos",
    "MPT / MG / Certidão Negativa de Feitos",
    "MPT / MS / Certidão Negativa de Feitos",
    "MPT / MT / Certidão Negativa de Feitos",
    "MPT / PB / Certidão Negativa de Feitos",
    "MPT / PE / Certidão Negativa de Feitos",
    "MPT / PI / Certidão Negativa de Feitos",
    "MPT / PR / Certidão Negativa de Feitos",
    "MPT / RJ / Certidão Negativa de Feitos",
    "MPT / RN / Certidão Negativa de Feitos",
    "MPT / RS / Certidão Negativa de Feitos",
    "MPT / SC / Certidão Negativa de Feitos",
    "MPT / SE / Certidão Negativa de Feitos",
    "MPT / SP / Campinas / Certidão Negativa de Feitos",
    "MPT / SP / Certidão Negativa de Feitos",
    "MPT / Unificada / Certidão Negativa de Feitos",
    "MTE / Certidão de Débitos Trabalhistas",
    "OFAC / Sanções",
    "ONU / Sanções",
    "Portal da Transparência / Acordos de Leniência",
    "Portal da Transparência / Auxílio Emergencial",
    "Portal da Transparência / Benefício de Prestação Continuada - BPC",
    "Portal da Transparência / Bolsa Família",
    "Portal da Transparência / Busca",
    "Portal da Transparência / Cadastro de Empresas Inidôneas e Suspensas (CEIS)",
    "Portal da Transparência / Cadastro de Entidades Privadas sem Fins Lucrativos Impedidas (CEPIM)",
    "Portal da Transparência / Cadastro de Expulsões da Administração Federal (CEAF)",
    "Portal da Transparência / Cadastro Nacional de Empresas Punidas (CNEP)",
    "Portal da Transparência / Convênios e Acordos",
    "Portal da Transparência / Garantia-Safra",
    "Portal da Transparência / Programa de Erradicação do Trabalho Infantil - PETI",
    "Portal da Transparência / Repasse de Verba",
    "Portal da Transparência / Seguro Defeso",
    "Prefeitura / AP / Macapá / Certidão Negativa de Débitos",
    "Prefeitura / AP / Santana / Certidão Negativa de Débitos",
    "Prefeitura / BA / Camaçari / Certidão Negativa de Débitos",
    "Prefeitura / BA / Ilhéus / Certidão Negativa de Débitos",
    "Prefeitura / BA / Juazeiro / Certidão Negativa de Débitos",
    "Prefeitura / BA / Salvador / Certidão Negativa de Débitos",
    "Prefeitura / BA / Salvador / Nada Consta",
    "Prefeitura / BA / Salvador / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / CE / Fortaleza / Certidão Negativa de Débitos",
    "Prefeitura / CE / Fortaleza / CPOM",
    "Prefeitura / CE / Jaguaretama / Certidão Negativa de Débitos",
    "Prefeitura / CPOM",
    "Prefeitura / GO / Anápolis / Certidão Negativa de Débitos",
    "Prefeitura / GO / Aparecida de Goiânia / Certidão Negativa de Débitos",
    "Prefeitura / GO / Campos Verdes / Certidão Negativa de Débitos",
    "Prefeitura / GO / Catalão / Certidão Negativa de Débitos",
    "Prefeitura / GO / Firminópolis / Certidão Negativa de Débitos",
    "Prefeitura / GO / Goiânia / Certidão Negativa de Débitos",
    "Prefeitura / GO / Itumbiara / Certidão Negativa de Débitos",
    "Prefeitura / GO / Jataí / Certidão Negativa de Débitos",
    "Prefeitura / GO / Morrinhos / Certidão Negativa de Débitos",
    "Prefeitura / GO / Perolândia / Licitações",
    "Prefeitura / GO / Rio Verde / Certidão Negativa de Débitos",
    "Prefeitura / GO / Uruaçu / Certidão Negativa de Débitos",
    "Prefeitura / MA / Balsas / Certidão Negativa de Débitos",
    "Prefeitura / MA / São Luís / Certidão Negativa de Débitos",
    "Prefeitura / MG / Araújos / Certidão Negativa de Débitos",
    "Prefeitura / MG / Belo Horizonte / Certidão Negativa de Débitos",
    "Prefeitura / MG / Belo Horizonte / Certidão Negativa de Débitos (IPTU)",
    "Prefeitura / MG / Belo Horizonte / IPTU (Emissão Guia)",
    "Prefeitura / MG / Contagem / Certidão Negativa de Débitos",
    "Prefeitura / MG / Contagem / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / MG / Divinópolis / Certidão Negativa de Débitos",
    "Prefeitura / MG / Dores do Indaiá / Certidão Negativa de Débitos",
    "Prefeitura / MG / Itaúna / Certidão Negativa de Débitos",
    "Prefeitura / MG / Janaúba / Certidão Negativa de Débitos",
    "Prefeitura / MG / Juatuba / Certidão Negativa de Débitos",
    "Prefeitura / MG / Luz / Certidão Negativa de Débitos",
    "Prefeitura / MG / Martinho Campos / Certidão Negativa de Débitos",
    "Prefeitura / MG / Nova Serrana / Certidão Negativa de Débitos",
    "Prefeitura / MG / Pará de Minas / Certidão Negativa de Débitos",
    "Prefeitura / MG / Santa Vitória / Certidão Negativa de Débitos",
    "Prefeitura / MG / Ubá / Certidão Negativa de Débitos",
    "Prefeitura / MG / Uberaba / Certidão Negativa de Débitos",
    "Prefeitura / MG / Uberlândia / Certidão Negativa de Débitos",
    "Prefeitura / MS / Calculadora de Fretes",
    "Prefeitura / MS / Campo Grande / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / MS / Chapadão do Sul / Certidão Negativa de Débitos",
    "Prefeitura / MS / Mundo Novo / Certidão Negativa de Débitos",
    "Prefeitura / MS / Naviraí / Certidão Negativa de Débitos",
    "Prefeitura / MT / Cuiabá / Certidão Negativa de Débitos",
    "Prefeitura / MT / Cuiabá / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / MT / Rondonópolis / Certidão Negativa de Débitos",
    "Prefeitura / PA / Belém / Multas",
    "Prefeitura / PA / Itaituba / Certidão Negativa de Débitos",
    "Prefeitura / PB / Campina Grande / Multas",
    "Prefeitura / PB / Mataraca / Certidão Negativa de Débitos",
    "Prefeitura / PE / Petrolina / Multas",
    "Prefeitura / PE / Recife / Certidão Negativa de Débitos",
    "Prefeitura / PE / Recife / CPOM",
    "Prefeitura / PE / Recife / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / PR / Ampére / Certidão Negativa de Débitos",
    "Prefeitura / PR / Curitiba / Certidão Negativa de Débitos",
    "Prefeitura / PR / Francisco Beltrão / Certidão Negativa de Débitos",
    "Prefeitura / PR / Maringá / Certidão Negativa de Débitos (Contribuinte)",
    "Prefeitura / RJ / Duque de Caxias / Certidão Negativa de Débitos",
    "Prefeitura / RJ / Rio de Janeiro / Certidão de Elementos Cadastrais - IPTU",
    "Prefeitura / RJ / Rio de Janeiro / Certidão Negativa de Débitos",
    "Prefeitura / RJ / Rio de Janeiro / Certidão Tributária de IPTU",
    "Prefeitura / RJ / Rio de Janeiro / CPOM",
    "Prefeitura / RJ / Rio de Janeiro / Emissão de IPTU",
    "Prefeitura / RJ / Rio de Janeiro / Multas (Descritivos)",
    "Prefeitura / RJ / Rio de Janeiro / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / RN / Natal / Certidão Negativa de Débitos",
    "Prefeitura / RN / Touros / Certidão Negativa de Débitos",
    "Prefeitura / RS / Caxias do Sul / Certidão Negativa de Débitos",
    "Prefeitura / RS / Farroupilha / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / RS / Montenegro / Certidão Negativa de Débitos",
    "Prefeitura / RS / Porto Alegre / Certidão Negativa de Débitos",
    "Prefeitura / RS / Porto Alegre / Comprovante de Inscrição do ISSQN",
    "Prefeitura / RS / Santa Cruz do Sul / Certidão Negativa de Débitos",
    "Prefeitura / RS / Três Coroas / Certidão Negativa de Débitos",
    "Prefeitura / SC / Balneário Camboriú / Certidão Negativa de Débitos",
    "Prefeitura / SC / Blumenau / Certidão Negativa de Débitos",
    "Prefeitura / SC / Florianópolis / Certidão Negativa de Débitos",
    "Prefeitura / SC / Imbituba / Certidão Negativa de Débitos",
    "Prefeitura / SC / Itajaí / Certidão Negativa de Débitos",
    "Prefeitura / SC / Joinville / Certidão Negativa de Débitos",
    "Prefeitura / SE / Laranjeiras / Certidão Negativa de Débitos",
    "Prefeitura / SP / Araçariguama / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / SP / Campinas / Certidão Negativa de Débitos",
    "Prefeitura / SP / Campinas / CPOM",
    "Prefeitura / SP / Campinas / Parcelas IPTU",
    "Prefeitura / SP / Campinas / Regularidade OTTC",
    "Prefeitura / SP / Guarulhos / Certidão Negativa de Débitos",
    "Prefeitura / SP / Hortolândia / Certidão Negativa de Débitos",
    "Prefeitura / SP / Jundiaí / Certidão Tributária de IPTU",
    "Prefeitura / SP / Mairiporã / Certidão Negativa de Débitos",
    "Prefeitura / SP / Mogi das Cruzes / CPOM",
    "Prefeitura / SP / Osasco / Certidão de Tributos de Empresa",
    "Prefeitura / SP / Osasco / Certidão Tributária de IPTU",
    "Prefeitura / SP / São Bernardo do Campo / Certidão Negativa de Débitos",
    "Prefeitura / SP / São Paulo / 2ª Via da Taxa de Elevadores",
    "Prefeitura / SP / São Paulo / AIT",
    "Prefeitura / SP / São Paulo / AIT (Últimos 36 meses)",
    "Prefeitura / SP / São Paulo / CADIN",
    "Prefeitura / SP / São Paulo / Caixa Postal",
    "Prefeitura / SP / São Paulo / CCM",
    "Prefeitura / SP / São Paulo / Certidão de Dados Cadastrais do Imóvel",
    "Prefeitura / SP / São Paulo / Certidão Tributária de IPTU",
    "Prefeitura / SP / São Paulo / Certidão Tributária Mobiliária",
    "Prefeitura / SP / São Paulo / CPOM",
    "Prefeitura / SP / São Paulo / Débitos de IPTU",
    "Prefeitura / SP / São Paulo / Dívida Ativa",
    "Prefeitura / SP / São Paulo / DSV Digital",
    "Prefeitura / SP / São Paulo / Emissão Parcela Simples Nacional",
    "Prefeitura / SP / São Paulo / Multas",
    "Prefeitura / SP / São Paulo / Multas (Antiga)",
    "Prefeitura / SP / São Paulo / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / SP / São Paulo / Recursos de Multas",
    "Prefeitura / SP / São Paulo / Regularidade OTTC",
    "Prefeitura / SP / São Paulo / Segunda via Simplificada de IPTU",
    "Prefeitura / SP / São Paulo / Valor Venal de Referência",
    "Prefeitura / SP / São Paulo / NFS-e (OCR)",
    "Prefeitura / SP / Sorocaba / CPOM",
    "Prefeitura / SP / Sumaré / NFS-e (Nota Fiscal Eletrônica de Serviços)",
    "Prefeitura / TO / Colinas / Certidão Negativa de Débitos",
    "Prefeitura / TO / Palmas / Certidão Negativa de Débitos",
    "Procuradoria Geral do Estado / BA / Dívida Ativa",
    "Procuradoria Geral do Estado / CE / Dívida Ativa",
    "Procuradoria Geral do Estado / MT / Dívida Ativa",
    "Procuradoria Geral do Estado / RJ / Dívida Ativa",
    "Procuradoria Geral do Estado / SP / Certidão Negativa de Débitos Tributários",
    "Procuradoria Geral do Estado / SP / Dívida Ativa",
    "Procuradoria Geral do Estado / SP / Emissão de GARE de Liquidação",
    "Receita Federal / Agenda Tributária",
    "Receita Federal / Cafir",
    "Receita Federal / CTe",
    "Receita Federal / NFE",
    "Receita Federal / NFS-e",
    "Receita Federal / NIRF",
    "Receita Federal / PER/DCOMP",
    "Receita Federal / PGFN (CND Federal)",
    "Receita Federal / PGFN (CND Federal) - Lista Segunda Via",
    "Receita Federal / PGFN (CND Federal) - Nova",
    "Receita Federal / PGFN (CND Federal) - Segunda Via",
    "Receita Federal / PGFN / Lista de Devedores",
    "Receita Federal / SICALC / Gerar DARF",
    "Receita Federal / Sistema de Acréscimos Legais (SAL) / Dados Cadastrais",
    "Registradores (ARISP) / Certidão / Download de Certidão Digital",
    "Registradores (ARISP) / Certidão / Novo Pedido de Certidão Digital",
    "Registradores (ARISP) / Consulta de Informações da Conta",
    "Registradores (ARISP) / Consulta de Saldo",
    "Registradores (ARISP) / Matrícula / Download de Matrícula",
    "Registradores (ARISP) / Matrícula / Lista de Pedidos",
    "Registradores (ARISP) / Matrícula / Novo Pedido de Visualização de Matrícula",
    "Secretaria de Inspeção do Trabalho / Trabalho Escravo",
    "SEFAZ / AC / Certidão Negativa de Débitos",
    "SEFAZ / AL / Certidão Negativa de Débitos",
    "SEFAZ / AM / Certidão Negativa de Débitos",
    "SEFAZ / AM / Certidão Negativa de Débitos (Certificado Digital)",
    "SEFAZ / AP / Certidão Negativa de Débitos",
    "SEFAZ / BA / Certidão Negativa de Débitos",
    "SEFAZ / CE / Certidao de Regularidade",
    "SEFAZ / CE / Certidão Negativa de Débitos",
    "SEFAZ / Certidão Negativa de Débitos Estaduais",
    "SEFAZ / DF / Certidão de Dívida Ativa",
    "SEFAZ / DF / Certidão Negativa de Débitos",
    "SEFAZ / ES / Certidão Negativa de Débitos",
    "SEFAZ / ES / Certidão Negativa de Débitos (via login)",
    "SEFAZ / GO / Certidão Negativa de Débitos",
    "SEFAZ / MA / Certidão de Dívida Ativa",
    "SEFAZ / MA / Certidão Negativa de Débitos",
    "SEFAZ / MG / Certidão Negativa de Débitos",
    "SEFAZ / MS / Certidão Negativa de Débitos",
    "SEFAZ / MS / DTE / Caixa Postal",
    "SEFAZ / MT / Certidão Negativa de Débitos",
    "SEFAZ / PA / Certidão Negativa de Débitos",
    "SEFAZ / PA / DEC / Caixa Postal",
    "SEFAZ / PB / Certidão Negativa de Débitos",
    "SEFAZ / PB / Emissão Dar",
    "SEFAZ / PE / Certidão de Regularidade Fiscal",
    "SEFAZ / PE / Certidão Negativa de Débitos",
    "SEFAZ / PI / Solicitar Certidão Negativa da Dívida Ativa (CNDA)",
    "SEFAZ / PI / Solicitar Certidão Negativa de Débitos",
    "SEFAZ / PR / Certidão Negativa de Débitos",
    "SEFAZ / RJ / Certidão Negativa de Débitos",
    "SEFAZ / RJ / Certidão Negativa de Débitos (Certificado Digital)",
    "SEFAZ / RN / Certidão Negativa de Débitos",
    "SEFAZ / RO / Certidão Negativa de Débitos",
    "SEFAZ / RR / Certidão Negativa de Débitos",
    "SEFAZ / RS / Certidão Negativa de Débitos",
    "SEFAZ / SC / Certidão Negativa de Débitos",
    "SEFAZ / SE / Certidão Negativa de Débitos",
    "SEFAZ / SP / Certidão Negativa de Débitos",
    "SEFAZ / TO / Certidão Negativa de Débitos",
    "Sivisa / SP",
    "TCU / Certidão Negativa de Inabilitado ou Inidôneo",
    "TCU / Inabilitados",
    "TCU / Relação de Inidôneos",
    "Tribunal / TJBA / Certidão do 1º Grau",
    "Tribunal / TJDF / Nada Consta",
    "Tribunal / TJGO / Nada Consta",
    "Tribunal / TJMA / Nada Consta",
    "Tribunal / TJMG / Processo",
    "Tribunal / TJMS / Cadastro de Pedido de Certidão (1º grau)",
    "Tribunal / TJMS / Conferência de Certidão",
    "Tribunal / TJPA / Certidão Criminal",
    "Tribunal / TJPR / Processo",
    "Tribunal / TJRJ / Cadastro de Pedido de Certidão",
    "Tribunal / TJRJ / Processo",
    "Tribunal / TJRJ / Visualizar Certidão",
    "Tribunal / TJRS / Certidão do 1º Grau",
    "Tribunal / TJSC / Pedido de Certidão",
    "Tribunal / TJSC / Visualizar Certidão",
    "Tribunal / TJSP / Cadastro de Pedido de Certidão",
    "Tribunal / TJSP / Certidão Cível de 1º Grau",
    "Tribunal / TJSP / Colégio Recursal e Turma de Uniformização",
    "Tribunal / TJSP / Download da Certidão Cível de 1º Grau",
    "Tribunal / TJSP / Processos do 1º Grau",
    "Tribunal / TJSP / Processos do 2º Grau",
    "Tribunal / TJSP / Visualizar Certidão",
    "Tribunal / TJTO / Certidão Judicial",
    "Tribunal / TRF1 / Certidão Negativa Cível e Criminal",
    "Tribunal / TRF2 / Certidão Negativa Cível e Criminal",
    "Tribunal / TRF3 / Certidão de Distribuição",
    "Tribunal / TRF3 / Obter Certidão de Distribuição",
    "Tribunal / TRF4 / Certidão Negativa Cível e Criminal",
    "Tribunal / TRF5 / Certidão Negativa Cível e Criminal",
    "Tribunal / TRF6 / Certidão Negativa Cível e Criminal",
    "Tribunal / TRT1 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT10 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT10 / Certidão Eletrônica de Ações Trabalhistas (CEAT) - Processos Digitais",
    "Tribunal / TRT11 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT12 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT13 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT14 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT15 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT17 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT18 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT19 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT2 / Certidão Eletrônica de Ações Trabalhistas (CEAT) - Processos Digitais",
    "Tribunal / TRT2 / Certidão Eletrônica de Ações Trabalhistas (CEAT) - Processos Físicos",
    "Tribunal / TRT23 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT24 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT3 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT4 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT5 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT6 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT7 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT8 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TRT9 / Certidão Eletrônica de Ações Trabalhistas (CEAT)",
    "Tribunal / TSE / Processo Judicial Eletrônico (PJe)",
    "Tribunal / TST / Banco de Falências",
    "Tribunal / TST / CNDT",
    "Tribunal / TST / Validação de CNDT",
    "EU Financial Sanctions List (PF/PJ)",
]

pf_list = sorted(PF_EXCLUSIVO + AMBOS)
pj_list = sorted(PJ_EXCLUSIVO + AMBOS)


def make_styles():
    header_font  = Font(name="Calibri", bold=True, color=WHITE, size=11)
    header_fill  = PatternFill("solid", fgColor=TEAL)
    row_fill_alt = PatternFill("solid", fgColor=GRAY_LIGHT)
    center       = Alignment(horizontal="center", vertical="center")
    left         = Alignment(horizontal="left",   vertical="center", wrap_text=True)
    thin         = Side(style="thin", color="CCCCCC")
    border       = Border(left=thin, right=thin, top=thin, bottom=thin)
    return header_font, header_fill, row_fill_alt, center, left, border


def build_sheet(ws, title, items):
    hf, hfill, alt_fill, center, left, border = make_styles()

    ws.title = title
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 6
    ws.column_dimensions["B"].width = 65

    # Header
    for col, label in enumerate(["Nº", "Fonte"], start=1):
        cell = ws.cell(row=1, column=col, value=label)
        cell.font       = hf
        cell.fill       = hfill
        cell.alignment  = center
        cell.border     = border
    ws.row_dimensions[1].height = 22

    # Data rows
    for i, item in enumerate(items, start=1):
        row = i + 1
        fill = alt_fill if i % 2 == 0 else None

        num_cell = ws.cell(row=row, column=1, value=i)
        num_cell.alignment = center
        num_cell.border    = border
        if fill:
            num_cell.fill = fill

        txt_cell = ws.cell(row=row, column=2, value=item)
        txt_cell.alignment = left
        txt_cell.border    = border
        if fill:
            txt_cell.fill = fill

        ws.row_dimensions[row].height = 16

    # Freeze header
    ws.freeze_panes = "A2"


wb = openpyxl.Workbook()
wb.remove(wb.active)  # remove default sheet

build_sheet(wb.create_sheet(), "Pessoa Física",   pf_list)
build_sheet(wb.create_sheet(), "Pessoa Jurídica", pj_list)

wb.save(OUTPUT)
print(f"Arquivo gerado: {OUTPUT}")
print(f"  Pessoa Física:   {len(pf_list)} buscas")
print(f"  Pessoa Jurídica: {len(pj_list)} buscas")
